pages:
  stage: deploy
  image: ruby:2.6
  script:
    - rm -rf public
    - mkdir public
    # copy everything at repo root EXCEPT the public dir itself
    - find . -maxdepth 1 -mindepth 1 ! -name public -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public
  only:
    - main
